- title: ออกแบบและปรับปรุงอคูสติก
  image: space-1.jpg
  content: 'เพื่อให้การใช้งานทางด้านเสียง มีประสิทธิภาพสูงสุด ต้องแก้ไขหรือปรับปรุงสภาพทางอคูสติค(Acoustic) ของห้อง ซึ่งสามารถดำเนินการได้ตั้งแต่ขั้นออกแบบก่อนการก่อสร้างหรือตบแต่งไปจนถึง การ ปรับปรุง แก้ไขของเดิม'

- title: ระบบเสียง ภาพ แสงไฟเวที และประชุมทางไกล ภาพและเสียง
  image: space-2.jpg
  content: 'เพื่อวัตถุประสงค์ต่าง ๆ อาทิเช่นระบบเสียงสำหรับห้องประชุมทุกประเภท หอประชุมเวทีการแสดง, ศูนย์ฝึกอบรม โรงแรม รวมทั้งการประชุมเสียงและภาพที่สามารถสื่อสารได้ถึงกันทั่วโลก โดยผ่านระบบ Video Conference เสมือนย่อโลกให้มาอยู่ในที่ประชุมบนโต๊ะเดียวกันได้'

- title: ระบบมัลติมีเดีย
  image: space-3.jpg
  content: 'เป็นการนำเสนอสื่อต่างๆ ที่จัดทำผ่านเครื่องฉายภาพชนิดต่างๆ เพื่อการนำเสนอสื่อผ่านระบบจอ LED DISPLAY ขนาดใหญ่  ระบบภาพเพื่อโฆษณา การศึกษาและความบันเทิง และ War Room, Control Room ต่างๆ'

- title: ระบบควบคุมอัตโนมัติ
  image: space-4.jpg
  content: 'สำหรับห้องประชุมที่ใช้การควบคุมงานระบบเสียง ภาพและแสง ที่ยุ่งยาก ให้ง่ายดายเพียงสัมผัสหน้าจอ เพื่อที่ต้องการความสะดวกและแม่นยำอย่างสูงในการควบคุมระบบโดยคนเดียว'

- title: ระบบเครือข่าย เอวี (Digital Signage)
  image: space-5.jpg
  content: 'เป็นการนำเสนอสื่อต่างๆ ในรูปเสียงภาพหรือระบบโฆษณาประชาสัมพันธ์ผ่านเครือข่าย คอมพิวเตอร์ ออกสู่หน้าจอแสดงผล ตามพื้นที่ต่างๆ ที่ต้องการ'

- title: ควบคุมแสงภายในอาคาร (Dimming Control System)
  image: space-1.jpg
  content: 'ควบคุมและจัดการแสงไฟเพื่อการประหยัดพลังงาน โดยใช้เครื่องหรี่ไฟและควบการเปิด-ปิด หลอดไฟโดยแบ่งพื้นที่ตามความเหมาะสมในการใช้งานในแต่ละช่วงเวลาของวัน โดยอัตโนมัติ'